add nsqd
BeeInventor/charts pull request #2
Opened 2021-07-15 02:25 UTC by Ashtonian

#1

2021-07-15 02:56 UTC, benjamin658 commented on beeinventor/nsq/templates/nsqd-statefulset.yaml
> +      resources:
We should allow users to specify the storage class.

```
{{- if ne "-" .Values.nsqd.storageClass }}
storageClassName: {{ .Values.nsqd.storageClass }}
{{- end -}}
```

2021-07-15 02:56 UTC, benjamin658 commented on beeinventor/nsq/values.yaml
> +
```
storageClass: "-"
```

2021-07-15 02:58 UTC, benjamin658 commented
Hi @Ashtonian ,

Thanks for your contribution, and I have added some reviews.

2021-07-15 03:04 UTC, benjamin658 commented
And we also need a `nsqd service` to expose the 4150 and 4151 ports.

2021-07-15 03:42 UTC, benjamin658 commented on beeinventor/nsq/values.yaml
> +
Group the `storageSize` and  `storageClass` under the  `persistence` value

```
persistence:
  storageSize: 1Gi
  storageClass: "-"
```

Also, remember to update the statefulset value.

2021-07-15 03:46 UTC, benjamin658 reviewed
Add persistence value to nsqd.

2021-07-15 22:31 UTC, Ashtonian commented
made a pass

2021-07-15 23:24 UTC, Ashtonian commented
yea the volumes settings aren't quite right out of the box with no per, but I don't understand what the fix is..

2021-07-16 17:53 UTC, benjamin658 requested changes

2021-07-16 17:53 UTC, benjamin658 commented on beeinventor/nsq/templates/nsqd-statefulset.yaml
> +        persistentVolumeClaim:
I think the StatefulSet should use the `volumeClaimTemplates` instead of the `persistentVolumeClaim`.
This section should be removed.

2021-07-26 01:49 UTC, benjamin658 commented
Thanks, @Ashtonian 

 I will test the statefulset volume these days.

2021-07-28 01:33 UTC, benjamin658 requested changes
The nsqd service linting was failed, please remove the ending `-` of line 20.

2021-07-28 01:33 UTC, benjamin658 commented on beeinventor/nsq/templates/nsqd-service.yaml
> +    {{- include "nsq.nsqd.selectorLabels" . | indent 4 -}}
Please remove the ending `-`.

2021-08-02 07:13 UTC, benjamin658 commented on beeinventor/nsq/templates/nsqd-service.yaml
> +    {{- include "nsq.nsqd.selectorLabels" . | indent 4 -}}
It should be `nindent` instead, I will fix it.

2021-08-02 07:30 UTC, benjamin658 commented
The PR is good to go.
Thanks for your contribution.

2021-08-02 07:32 UTC, merged

2021-08-04 21:10 UTC, Ashtonian commented
thanks for finishing and merging, sorry was moving irl.