add missing docs, priority class, missing extra args
BeeInventor/charts pull request #7
Opened 2021-08-17 21:43 UTC by Ashtonian

#6

2021-08-19 01:34 UTC, benjamin658 requested changes
Correct the nsqd default replica.

2021-08-20 22:02 UTC, Ashtonian commented on beeinventor/nsq/README.md
> +| nsqd.replicaCount       | Number of nsqd replicas                                                              | `1`                  |
fixed!

2021-08-23 02:40 UTC, benjamin658 approved these changes

2021-08-23 02:43 UTC, benjamin658 commented
Hi @Ashtonian , Let's bump the chart version to 1.1.6, and the PR will be good to go.

2021-08-23 06:51 UTC, LordNoteworthy commented
Thank you for this !

2021-08-23 10:41 UTC, benjamin658 commented
> Thank you for this ! Let's get it merged :)

Waiting for @Ashtonian bump chart version in this PR.

2021-08-24 10:21 UTC, benjamin658 commented
I have created a new commit d9aa2e92ba763d2f2a7e2a2edde19a2fc7d01bd0 to bump the chart version to 1.1.6.

Thanks for your contribution!

2021-08-24 10:22 UTC, merged

2021-08-24 10:32 UTC, benjamin658 commented
@LordNoteworthy ,  extraArgs is supported in the new release.

The tarball has been committed accidentally in 1.1.6, so you better use the 1.1.7.

2021-08-24 11:21 UTC, LordNoteworthy commented
Thank you so much ! Much appreciated <3

2021-08-24 11:58 UTC, LordNoteworthy commented
Probably we missed something:

`{{ toYaml .Values.nsqadmin.extraArgs | indent 8 }}` should be `{{*-* toYaml .Values.nsqadmin.extraArgs | indent 8 }}`

Otherwise, we end up like this:

![image](https://user-images.githubusercontent.com/5129564/130612493-11221102-3e6d-4bff-9ed3-13fac1e9c0c0.png)